### ISSUE TITLE
How can we run this in production mode on a raspberry pi?

### ISSUE THREAD

**Issue by t-p** [ewal/react-spotbot-client#28]
In the "old" mnd-spotbot-client our setup was a [nginx](http://nginx.org/en/) serving the application. When i try this setup, i get an `Uncaught Error: [HMR] Hot Module Replacement is disabled.` I can run the app in development mode for now, but how can I run all this new and fancy JS stuff, like `Webpack, Webpack Dev Server and HotModuleReplacementPlugin` in production mode?

**Comment by ewal** [comment]
Can I close this?

**Comment by t-p** [comment]
sure
